<div id='cabecalho'>
	<h1><a href='/'>Novo Cântico</a></h1>
	<h2><a href='/'>Hinário Presbiteriano</a></h2>

	<div id='menu'>
		<ul>
			<li><a href='index.php?tipo=assunto'>Índice</a></li>
			<li><a href='artigos.php'>Artigos</a></li>
			<li><a href='sobre.php'>Sobre</a></li>
			<li><a href='contato.php'>Contato</a></li>
			<li><a href='hnc_v001.epub'>E-book (ePub)</a></li>
		</ul>

		<form action='http://www.novocantico.com.br/busca.php' id='cse-search-box'>
			<fieldset>
				<input type='text' name='q' id='busca' />
				<input type='hidden' name='cx' value='007541164279382477135:v55cgb2k3be' />
				<input type='hidden' name='cof' value='FORID:9' />
				<input type='hidden' name='ie' value='UTF-8' /> <button type='submit' name='sa'>Buscar</button>
			</fieldset>
		</form>
	</div>
</div>
