
		<ul id='indice_estatico'>
			<li>* <em>somente a letra</em></li>
			<li><span id='a'>A</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/093/093.xml'>A minha fé e o meu amor</a>: 093</li>
					<li><a href='hino/047/047.xml'>Aleluia! Toda a glória te rendemos, Senhor</a>: 047</li>
					<li><a href='hino/269/269.xml'>Alvo mais que a neve</a>: 269</li>
					<li><a href='hino/373/373.xml'>Ano findo nunca mais veremos</a>: 373</li>
					<li><a href='hino/254/254.xml'>“As ondas atendem ao meu mandar</a>: 254</li>
				</ul>
			</li>
			<li><span id='b'>B</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/320/320.xml'>Brilha no meio do teu viver</a>: 320</li>
					<li><a href='hino/362/362.xml'>Brilhando, brilhando</a>: 362</li>
					<li><a href='hino/114/114.xml'>Brilho celeste! Brilho celeste</a>: 114</li>
				</ul>
			</li>
			<li><span id='c'>C</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/115/115.xml'>Cada momento me guia o Senhor</a>: 115</li>
					<li><a href='hino/026/026.xml'>Canta minh'alma, então, a ti, Senhor</a>: 026</li>
					<li><a href='hino/104/104.xml'>Cantarei em meu coração, esta linda melodia</a>: 104</li>
					<li><a href='hino/172/172.xml'>Chuvas de bênçãos</a>: 172</li>
					<li><a href='hino/063/063.xml'>Conta as bênçãos, dize-as quantas são</a>: 063</li>
					<li><a href='hino/144/144.xml'>Conto esta história, cantando assim</a>: 144</li>
				</ul>
			</li>
			<li><span id='d'>D</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/274/274.xml'>Da sepultura saiu</a>: 274</li>
					<li><a href='hino/057/057.xml'>De todo bem a fonte</a>: 057</li>
				</ul>
			</li>
			<li><span id='e'>E</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/288/288.xml'>É a mensagem que me deu</a>: 288</li>
					<li><a href='hino/234/234.xml'>É este Jesus o Rei</a>: 234</li>
					<li><a href='hino/113/113.xml'>Ele é a Luz do mundo, a Estrela da Manhã</a>: 113</li>
					<li><a href='hino/031/031.xml'>És nosso Pai, ó Deus de amor</a>: 031 *</li>
					<li><a href='hino/030/030.xml'>Eterno Deus, ó Deus sem par</a>: 030 *</li>
					<li><a href='hino/014/014.xml'>Exaltado seja nosso Deus e Pai</a>: 014</li>
					<li><a href='hino/042/042.xml'>Exultai! Exultai! Vinde todos louvar</a>: 042</li>
					<li><a href='hino/240/240.xml'>Exultai, ó terra e céus</a>: 240</li>
				</ul>
			</li>
			<li><span id='f'>F</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/080/080.xml'>Falarei do grande amor</a>: 080</li>
					<li><a href='hino/177/177.xml'>Firme, firme</a>: 177</li>
				</ul>
			</li>
			<li><span id='g'>G</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/147/147.xml'>Glória, glória, aleluia</a>: 147</li>
					<li><a href='hino/062/062.xml'>Graças, graças, mil graças</a>: 062</li>
				</ul>
			</li>
			<li><span id='j'>J</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/161/161.xml'>Jesus é o melhor Amigo</a>: 161</li>
				</ul>
			</li>
			<li><span id='m'>M</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/222/222.xml'>Mais perto da tua cruz</a>: 222</li>
					<li><a href='hino/135/135.xml'>Mais,mais de Cristo</a>: 135</li>
					<li><a href='hino/038/038.xml'>Mil vezes, sim, mil vezes, sim</a>: 038</li>
				</ul>
			</li>
			<li><span id='n'>N</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/049/049.xml'>Não é dos fortes a vitória</a>: 049</li>
					<li><a href='hino/239/239.xml'>Nasce Jesus! Nasce Jesus</a>: 239</li>
					<li><a href='hino/231/231.xml'>Natal! Natal! Natal! Natal</a>: 231</li>
					<li><a href='hino/033/033.xml'>No céu, na terra, que maravilhas</a>: 033</li>
					<li><a href='hino/315/315.xml'>No labor, sem cessar</a>: 315</li>
					<li><a href='hino/145/145.xml'>No poder de Cristo, o Mestre</a>: 145</li>
					<li><a href='hino/027/027.xml'>Nos céus e no mar e na terra</a>: 027</li>
					<li><a href='hino/325/325.xml'>Nós crentes redimidas</a>: 325</li>
				</ul>
			</li>
			<li><span id='o'>O</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/268/268.xml'>O teu sangue foi vertido</a>: 268</li>
					<li><a href='hino/230/230.xml'>Ó! Vinde, adoremos</a>: 230</li>
					<li><a href='hino/146/146.xml'>Oh! Não temas! Oh não temas</a>: 146</li>
					<li><a href='hino/198/198.xml'>Oh! Olhai, com fé, olhai</a>: 198</li>
					<li><a href='hino/292/292.xml'>Oh! Que dia glorioso esse dia há de ser</a>: 292</li>
					<li><a href='hino/318/318.xml'>Os que esperam no Senhor renovar-se-ão</a>: 318</li>
				</ul>
			</li>
			<li><span id='p'>P</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/368/368.xml'>Pelo seu poder e no seu amor</a>: 368</li>
				</ul>
			</li>
			<li><span id='q'>Q</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/297/297.xml'>Quando enfim chegar o dia</a>: 297</li>
					<li><a href='hino/367/367.xml'>Que alegria, sem pecado ou mal</a>: 367</li>
				</ul>
			</li>
			<li><span id='s'>S</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/379/379.xml'>Salve Deus a minha Pátria</a>: 379</li>
					<li><a href='hino/084/084.xml'>Santo Espírito de Deus</a>: 084</li>
					<li><a href='hino/017/017.xml'>Seja louvado o Deus supremo</a>: 017</li>
					<li><a href='hino/151/151.xml'>Sempre amável e clemente</a>: 151</li>
					<li><a href='hino/266/266.xml'>Sim, eu amo a mensagem da cruz</a>: 266</li>
					<li><a href='hino/326/326.xml'>Sim, lutemos por Cristo Jesus</a>: 326</li>
					<li><a href='hino/108/108.xml'>Sou feliz com Jesus</a>: 108</li>
					<li><a href='hino/034/034.xml'>Sua graça Deus nos dá</a>: 034 *</li>
				</ul>
			</li>
			<li><span id='t'>T</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/032/032.xml'>Tu és fiel, Senhor! Tu és fiel, Senhor</a>: 032</li>
				</ul>
			</li>
			<li><span id='v'>V</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/286/286.xml'>Vamos nós obedecer! Vamos à colheita</a>: 286</li>
					<li><a href='hino/282/282.xml'>Vamos, irmãos, levar</a>: 282</li>
					<li><a href='hino/193/193.xml'>Vou à pátria - eu, peregrino -</a>: 193</li>
				</ul>
			</li>
		</ul>
