
		<ul id='indice_estatico'>
			<li>* <em>somente a letra</em></li>
			<li><span id='a'>A</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='AckleyAH'>Ackley, Alfred Henry: 
						<a href='hino/104/104.xml'>104</a>
					<li id='AgnusDei'>Agnus Dei: 
						<a href='hino/015/015.xml'>015</a>
					<li id='Anonimo'>Anônimo: 
						<a href='hino/017/017.xml'>017</a>, 
						<a href='hino/247/247.xml'>247</a>
					<li id='AntigaMelodiaHebraica'>Antiga Melodia Hebraica: 
						<a href='hino/021/021.xml'>021</a> *
					<li id='AvocatM'>Avocat, M.: 
						<a href='hino/088/088.xml'>088</a>
					</li>
				</ul>
			</li>
			<li><span id='b'>B</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='BachJS'>Bach, Johann Sebastian: 
						<a href='hino/264/264.xml'>264</a>
					<li id='BeethovenL'>Beethoven, Ludwig van: 
						<a href='hino/028/028.xml'>028</a>, 
						<a href='hino/A/A.xml'>A</a>
					<li id='BennardG'>Bennard, George: 
						<a href='hino/266/266.xml'>266</a>
					<li id='BilhornPB'>Bilhorn, Peter Philip: 
						<a href='hino/161/161.xml'>161</a>
					<li id='BlackJM'>Black, James Milton: 
						<a href='hino/297/297.xml'>297</a>
					<li id='BlankerburgerLieder'>“Blankerburger Lieder”: 
						<a href='hino/026/026.xml'>026</a>
					<li id='BlissPP'>Bliss, Philip Paul: 
						<a href='hino/108/108.xml'>108</a>, 
						<a href='hino/146/146.xml'>146</a>
					<li id='BorgeoisL'>Borgeois, Loys: 
						<a href='hino/006/006.xml'>006</a>
					<li id='BradburyWB'>Bradbury, William Batchelder: 
						<a href='hino/093/093.xml'>093</a>, 
						<a href='hino/127/127.xml'>127</a>, 
						<a href='hino/225/225.xml'>225</a>
					<li id='BragaHRF'>Braga, Henriqueta Rosa Fernandes: 
						<a href='hino/068/068.xml'>068</a>
					<li id='Bundes-Lieder'>“Bundes-Lieder”: 
						<a href='hino/004/004.xml'>004</a> *
					<li id='BuyersN'>Buyers, Norah: 
						<a href='hino/066/066.xml'>066</a>
					</li>
				</ul>
			</li>
			<li><span id='c'>C</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='CalkinJB'>Calkin, John Baptiste: 
						<a href='hino/212/212.xml'>212</a>
					<li id='CamidgeJ'>Camidge, John: 
						<a href='hino/012/012.xml'>012</a>
					<li id='CantiquesDuMessager'>“Cantiques du Messager”: 
						<a href='hino/088/088.xml'>088</a>
					<li id='CantusDiversi'>“Cantus Diversi”: 
						<a href='hino/230/230.xml'>230</a>
					<li id='CarterRK'>Carter, Russel Kelso: 
						<a href='hino/177/177.xml'>177</a>
					<li id='CarvalhoB'>Carvalho, Benedito de: 
						<a href='hino/326/326.xml'>326</a>
					<li id='CarvalhoE'>Carvalho, Eurípedes de: 
						<a href='hino/326/326.xml'>326</a>
					<li id='CasselFH'>Cassel, Flora Hamilton: 
						<a href='hino/288/288.xml'>288</a>
					<li id='ChurchPraiseColecao'>“Church Praise” (Coleção): 
						<a href='hino/148/148.xml'>148</a>
					<li id='ConceicaoLR'>Conceição, Leopoldina Ruth da: 
						<a href='hino/395/395.xml'>395</a>
					<li id='CookGH'>Cook, George H.: 
						<a href='hino/114/114.xml'>114</a>
					<li id='CopeM'>Cope, Mildred: 
						<a href='hino/084/084.xml'>084</a>
					<li id='CostaJr'>Costa Jr.: 
						<a href='hino/326/326.xml'>326</a>
					<li id='CruzL'>Cruz, Luiza: 
						<a href='hino/247/247.xml'>247</a>
					<li id='CummingsWH'>Cummings, William Hayman: 
						<a href='hino/240/240.xml'>240</a>
					<li id='CurryL'>Curry, Lawrence: 
						<a href='hino/010/010.xml'>010</a> *
					</li>
				</ul>
			</li>
			<li><span id='d'>D</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='DoaneWH'>Doane, William Howard: 
						<a href='hino/042/042.xml'>042</a>, 
						<a href='hino/222/222.xml'>222</a>, 
						<a href='hino/315/315.xml'>315</a>
					<li id='DykesJB'>Dykes, John Bacchus: 
						<a href='hino/011/011.xml'>011</a>, 
						<a href='hino/035/035.xml'>035</a> *
					</li>
				</ul>
			</li>
			<li><span id='e'>E</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='EllorJ'>Ellor, James: 
						<a href='hino/052/052.xml'>052</a>
					<li id='ExcellEO'>Excell, Edwin Othello: 
						<a href='hino/063/063.xml'>063</a>, 
						<a href='hino/362/362.xml'>362</a>
					</li>
				</ul>
			</li>
			<li><span id='f'>F</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='FaustiniJW'>Faustini, João Wilson: 
						<a href='hino/190/190.xml'>190</a>
					<li id='FestgesangCantata'>“Festgesang” (Cantata): 
						<a href='hino/240/240.xml'>240</a>
					<li id='FischerWG'>Fischer, William Gustavus: 
						<a href='hino/325/325.xml'>325</a>
					<li id='FlemmingFF'>Flemming, Friedrich Ferdinand: 
						<a href='hino/064/064.xml'>064</a>
					<li id='FryCW'>Fry, Charles William: 
						<a href='hino/113/113.xml'>113</a>
					</li>
				</ul>
			</li>
			<li><span id='g'>G</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='GabrielCH'>Gabriel, Charles Hutchinson: 
						<a href='hino/027/027.xml'>027</a>, 
						<a href='hino/286/286.xml'>286</a>, 
						<a href='hino/320/320.xml'>320</a>, 
						<a href='hino/014/014.xml'>014</a>
					<li id='GeistlichKirchengesangColecao'>“Geistlich Kirchengesang” (Coleção): 
						<a href='hino/010/010.xml'>010</a> *
					<li id='GeistlicheLieder'>“Geistliche Lieder”: 
						<a href='hino/229/229.xml'>229</a>
					<li id='GeorgeHL'>George H. Loud: 
						<a href='hino/148/148.xml'>148</a>
					<li id='GossJ'>Goss, John: 
						<a href='hino/374/374.xml'>374</a>
					<li id='GoudimelC'>Goudimel, Claude: 
						<a href='hino/006/006.xml'>006</a>
					<li id='GruberFX'>Gruber, Franz Xaver: 
						<a href='hino/243/243.xml'>243</a>
					<li id='GuimaraesS'>Guimarães, Sebastião: 
						<a href='hino/332/332.xml'>332</a>
					</li>
				</ul>
			</li>
			<li><span id='h'>H</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='HaendelGF'>Haendel, Georg Friedrich: 
						<a href='hino/237/237.xml'>237</a>
					<li id='HallJL'>Hall, Joseph Lincoln: 
						<a href='hino/193/193.xml'>193</a>
					<li id='HasslerHL'>Hassler, Hans Leo: 
						<a href='hino/264/264.xml'>264</a>
					<li id='HastingsT'>Hastings, Thomas: 
						<a href='hino/136/136.xml'>136</a>
					<li id='HavergalWH'>Havergal, William Henry: 
						<a href='hino/340/340.xml'>340</a>
					<li id='HaydnFJ'>Haydn, Franz Joseph: 
						<a href='hino/022/022.xml'>022</a> *
					<li id='HayneLG'>Hayne, Leighton George: 
						<a href='hino/208/208.xml'>208</a>
					<li id='HerbstM'>Herbst, Martin: 
						<a href='hino/216/216.xml'>216</a>
					</li>
				</ul>
			</li>
			<li><span id='i'>I</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='IchterBH'>Ichter, Bill H.: 
						<a href='hino/379/379.xml'>379</a>
					<li id='IronsHS'>Irons, Herbert Stephen: 
						<a href='hino/375/375.xml'>375</a>
					</li>
				</ul>
			</li>
			<li><span id='j'>J</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='JarmanT'>Jarman, Thomas: 
						<a href='hino/139/139.xml'>139</a>
					<li id='JerseyJ'>Jersey, Jeferson: 
						<a href='hino/002/002.xml'>002</a>
					</li>
				</ul>
			</li>
			<li><span id='k'>K</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='K194'>K. 194: 
						<a href='hino/015/015.xml'>015</a>
					<li id='KentJ'>Kent, James: 
						<a href='hino/015/015.xml'>015</a>
					<li id='KettringDD'>Kettring, Donald D.: 
						<a href='hino/011/011.xml'>011</a>
					<li id='KikpatrickWJ'>Kikpatrick, William James: 
						<a href='hino/038/038.xml'>038</a>
					<li id='Klug, J'>Klug, Joseph: 
						<a href='hino/155/155.xml'>155</a>
					<li id='KnappPP'>Knapp, Phoebe Palmer: 
						<a href='hino/144/144.xml'>144</a>
					<li id='KochM'>Koch, Mina: 
						<a href='hino/154/154.xml'>154</a>
					<li id='KocherC'>Kocher, Conrad: 
						<a href='hino/371/371.xml'>371</a>
					</li>
				</ul>
			</li>
			<li><span id='l'>L</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='LeoniM'>Leoni, Michael: 
						<a href='hino/021/021.xml'>021</a> *
					<li id='LinseyEV'>Linsey, Emily V.: 
						<a href='hino/379/379.xml'>379</a>
					<li id='LowryR'>Lowry, Robert: 
						<a href='hino/013/013.xml'>013</a>, 
						<a href='hino/239/239.xml'>239</a>, 
						<a href='hino/274/274.xml'>274</a>
					<li id='LuteroM'>Lutero, Martinho: 
						<a href='hino/155/155.xml'>155</a>
					</li>
				</ul>
			</li>
			<li><span id='m'>M</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='MakerFC'>Maker, Frederick Charles: 
						<a href='hino/048/048.xml'>048</a>, 
						<a href='hino/399/399.xml'>399</a>
					<li id='ManuelRE'>Manuel, Ralph Eugene: 
						<a href='hino/001/001.xml'>001</a>, 
						<a href='hino/033/033.xml'>033</a>, 
						<a href='hino/062/062.xml'>062</a>, 
						<a href='hino/071/071.xml'>071</a>, 
						<a href='hino/093/093.xml'>093</a>, 
						<a href='hino/145/145.xml'>145</a>, 
						<a href='hino/332/332.xml'>332</a>
					<li id='MasonL'>Mason, Lowell: 
						<a href='hino/001/001.xml'>001</a>, 
						<a href='hino/116/116.xml'>116</a>, 
						<a href='hino/183/183.xml'>183</a>
					<li id='MaunderJH'>Maunder, John Henry: 
						<a href='hino/030/030.xml'>030</a> *, 
						<a href='hino/031/031.xml'>031</a> *
					<li id='McGranahamJ'>McGranaham, James: 
						<a href='hino/172/172.xml'>172</a>
					<li id='McGranahanJ'>McGranahan, James: 
						<a href='hino/318/318.xml'>318</a>
					<li id='MeinekeC'>Meineke, Charles: 
						<a href='hino/005/005.xml'>005</a>
					<li id='MelodiaAlema'>Melodia Alemã: 
						<a href='hino/034/034.xml'>034</a> *, 
						<a href='hino/346/346.xml'>346</a>
					<li id='MelodiaDinamarquesa'>Melodia dinamarquesa: 
						<a href='hino/B/B.xml'>B</a>
					<li id='MelodiaGalesa'>Melodia galesa: 
						<a href='hino/080/080.xml'>080</a>, 
						<a href='hino/299/299.xml'>299</a>, 
						<a href='hino/317/317.xml'>317</a>
					<li id='MelodiaInglesa'>Melodia inglesa: 
						<a href='hino/231/231.xml'>231</a>, 
						<a href='hino/234/234.xml'>234</a>
					<li id='MelodiaMaori'>Melodia maori: 
						<a href='hino/067/067.xml'>067</a>
					<li id='MelodiaSueca'>Melodia sueca: 
						<a href='hino/026/026.xml'>026</a>
					<li id='MendelssohnBF'>Mendelssohn-Bartholdy, Felix: 
						<a href='hino/240/240.xml'>240</a>
					<li id='MissaBreveReMaior'>Missa Breve em Ré Maior: 
						<a href='hino/015/015.xml'>015</a>
					<li id='MoodyMW'>Moody, Mary Whittle: 
						<a href='hino/115/115.xml'>115</a>
					<li id='MozartWA'>Mozart, Wolfgang Amadeus: 
						<a href='hino/015/015.xml'>015</a>
					</li>
				</ul>
			</li>
			<li><span id='n'>N</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='NaegeliJG'>Naegeli, Johann Georg: 
						<a href='hino/183/183.xml'>183</a>
					<li id='NeanderJ'>Neander, Joachim: 
						<a href='hino/004/004.xml'>004</a> *
					<li id='NiemeyerE'>Niemeyer, Edouard: 
						<a href='hino/003/003.xml'>003</a> *
					<li id='NogueiraE'>Nogueira, Edilson: 
						<a href='hino/062/062.xml'>062</a>
					<li id='NonaSinfoniaCoral'>Nona Sinfonia (Coral): 
						<a href='hino/028/028.xml'>028</a>
					<li id='NurnbergischesGesangbuch'>“Nürnbergisches Gesangbuch”: 
						<a href='hino/216/216.xml'>216</a>
					</li>
				</ul>
			</li>
			<li><span id='o'>O</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='OgdenWA'>Ogden, William Augustine: 
						<a href='hino/198/198.xml'>198</a>
					<li id='OratorioMessias'>Oratório Messias: 
						<a href='hino/237/237.xml'>237</a>
					</li>
				</ul>
			</li>
			<li><span id='p'>P</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='PalmerHR'>Palmer, Horatio Richmond: 
						<a href='hino/254/254.xml'>254</a>, 
						<a href='hino/282/282.xml'>282</a>
					<li id='PerkinsHS'>Perkins, Henry Southwick: 
						<a href='hino/269/269.xml'>269</a>
					<li id='PortugalV'>Portugal, Volmer: 
						<a href='hino/002/002.xml'>002</a>
					<li id='PraxisPietatisMelica'>“Praxis Pietatis Melica”: 
						<a href='hino/016/016.xml'>016</a>
					<li id='ProutE'>Prout, Ebenezer: 
						<a href='hino/007/007.xml'>007</a> *
					</li>
				</ul>
			</li>
			<li><span id='r'>R</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='ReamA'>Ream, Alberto: 
						<a href='hino/243/243.xml'>243</a>
					<li id='ReamAW'>Ream, Albert Willard: 
						<a href='hino/017/017.xml'>017</a>
					<li id='RevivalTuneBookColecao'>“Revival Tune Book” (Coleção): 
						<a href='hino/047/047.xml'>047</a>
					<li id='RootGF'>Root, George Frederick: 
						<a href='hino/367/367.xml'>367</a>
					<li id='RounsefellCEP'>Rounsefell, Carrie Esther Parker: 
						<a href='hino/327/327.xml'>327</a>
					<li id='RousseauJJ'>Rousseau, Jean-Jacques: 
						<a href='hino/029/029.xml'>029</a> *
					<li id='RunyanWM'>Runyan, William Marion: 
						<a href='hino/032/032.xml'>032</a>
					<li id='RussoV'>Russo, Vicente: 
						<a href='hino/190/190.xml'>190</a>
					</li>
				</ul>
			</li>
			<li><span id='s'>S</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='SacredMelodyColecao'>“Sacred Melody” (Coleção): 
						<a href='hino/171/171.xml'>171</a>
					<li id='SalterioGenebra'>“Saltério de Genebra”: 
						<a href='hino/006/006.xml'>006</a>
					<li id='SankeyID'>Sankey, Ira David: 
						<a href='hino/037/037.xml'>037</a>, 
						<a href='hino/113/113.xml'>113</a>, 
						<a href='hino/226/226.xml'>226</a>
					<li id='SantosRR'>Santos, Renato Ribeiro dos: 
						<a href='hino/066/066.xml'>066</a>
					<li id='SchubertF'>Schubert, Franz: 
						<a href='hino/151/151.xml'>151</a>
					<li id='SchulzJAP'>Schulz, Johann Abraham Peter: 
						<a href='hino/057/057.xml'>057</a>
					<li id='SibeliusJJC'>Sibelius, Johan Julius Christian: 
						<a href='hino/156/156.xml'>156</a>
					<li id='SosaPD'>Sosa, Pablo D.: 
						<a href='hino/071/071.xml'>071</a>
					<li id='Stainer, J'>Stainer, John: 
						<a href='hino/231/231.xml'>231</a>
					<li id='StainerJ'>Stainer, John: 
						<a href='hino/C/C.xml'>C</a>
					<li id='StebbinsGC'>Stebbins, George Coles: 
						<a href='hino/033/033.xml'>033</a>, 
						<a href='hino/128/128.xml'>128</a>, 
						<a href='hino/131/131.xml'>131</a>, 
						<a href='hino/218/218.xml'>218</a>
					<li id='SteffeJW'>Steffe, John William: 
						<a href='hino/147/147.xml'>147</a>
					<li id='StralsundGesangbuch'>“Stralsund Gesangbuch”: 
						<a href='hino/016/016.xml'>016</a>
					<li id='SweneyJR'>Sweney, John Robson: 
						<a href='hino/049/049.xml'>049</a>, 
						<a href='hino/135/135.xml'>135</a>, 
						<a href='hino/292/292.xml'>292</a>
					</li>
				</ul>
			</li>
			<li><span id='t'>T</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='TheHymnal'>“The Hymnal”: 
						<a href='hino/156/156.xml'>156</a>
					<li id='TomerWG'>Tomer, William Gould: 
						<a href='hino/368/368.xml'>368</a>
					<li id='TuckerH'>Tucker, Henry: 
						<a href='hino/373/373.xml'>373</a>
					</li>
				</ul>
			</li>
			<li><span id='w'>W</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='WadeJohnF'>Wade, John Francis: 
						<a href='hino/230/230.xml'>230</a>
					<li id='WarrenGW'>Warren, George William: 
						<a href='hino/018/018.xml'>018</a>
					<li id='WesleySS'>Wesley, Samuel Sebastian: 
						<a href='hino/298/298.xml'>298</a>
					<li id='WhishawA'>Whishaw, Alexander: 
						<a href='hino/268/268.xml'>268</a>
					<li id='WhyteJM'>Whyte, J.M.: 
						<a href='hino/145/145.xml'>145</a>
					<li id='WilkesJB'>Wilkes, John Bernard: 
						<a href='hino/034/034.xml'>034</a> *
					<li id='WilliamTJ'>William, Thomas John: 
						<a href='hino/299/299.xml'>299</a>
					<li id='WittenbergGesangbuch'>“Wittenberg Gesangbuch”: 
						<a href='hino/155/155.xml'>155</a>
					</li>
				</ul>
			</li>
			<li><span id='z'>Z</span> <a href='#conteudo'>topo</a>
				<ul>
					<li id='ZimmermannA'>Zimmermann, Alfonso: 
						<a href='hino/225/225.xml'>225</a>, 
						<a href='hino/318/318.xml'>318</a>
					<li id='ZionsharfeColecao'>“Zionsharfe” (Coleção): 
						<a href='hino/371/371.xml'>371</a>
					</li>
				</ul>
			</li>
		</ul>
