
		<ul id='indice_estatico'>
			<li>* <em>somente a letra</em></li>
			<li><span id='a'>A</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/042/042.xml'>A Deus demos glória por seu grande amor</a>: 042</li>
					<li><a href='hino/006/006.xml'>A Deus, supremo Benfeitor</a>: 006</li>
					<li><a href='hino/325/325.xml'>A nós aqui reunidas</a>: 325</li>
					<li><a href='hino/057/057.xml'>A terra semeamos a fim de nos dar pão</a>: 057</li>
					<li><a href='hino/007/007.xml'>A ti, meu Criador</a>: 007 *</li>
					<li><a href='hino/216/216.xml'>Acharei mercê em Deus</a>: 216</li>
					<li><a href='hino/113/113.xml'>Achei um bom amigo, Jesus, o Salvador</a>: 113</li>
					<li><a href='hino/212/212.xml'>Alma, escuta o bom Senhor</a>: 212</li>
					<li><a href='hino/022/022.xml'>Altamente os céus proclamam</a>: 022 *</li>
					<li><a href='hino/088/088.xml'>Amavas-me, Senhor, ainda cintilante</a>: 088</li>
					<li><a href='hino/C/C.xml'>Amém, amém, amém, amém</a>: C</li>
					<li><a href='hino/B/B.xml'>Amém, amém, amém</a>: B</li>
					<li><a href='hino/374/374.xml'>Ano velho já findado</a>: 374</li>
					<li><a href='hino/021/021.xml'>Ao Deus de Abraão louvai, do vasto céu Senhor</a>: 021 *</li>
					<li><a href='hino/033/033.xml'>Ao Deus de amor e de imensa bondade</a>: 033</li>
					<li><a href='hino/327/327.xml'>Aqui reunidos, queremos, ó Deus</a>: 327</li>
					<li><a href='hino/027/027.xml'>As grutas, as rochas imensas</a>: 027</li>
				</ul>
			</li>
			<li><span id='b'>B</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/127/127.xml'>Bendita hora de oração</a>: 127</li>
					<li><a href='hino/183/183.xml'>Benditos laços são</a>: 183</li>
				</ul>
			</li>
			<li><span id='c'>C</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/080/080.xml'>Cantarei o imenso amor</a>: 080</li>
					<li><a href='hino/155/155.xml'>Castelo forte é nosso Deus</a>: 155</li>
					<li><a href='hino/318/318.xml'>Ceifeiros da Seara santa</a>: 318</li>
					<li><a href='hino/286/286.xml'>Ceifeiros somos nós, fiéis</a>: 286</li>
					<li><a href='hino/208/208.xml'>Chegai-vos ao Senhor com puro coração</a>: 208</li>
					<li><a href='hino/172/172.xml'>Chuvas de bênçãos teremos</a>: 172</li>
					<li><a href='hino/115/115.xml'>Com Cristo unido na morte da cruz</a>: 115</li>
					<li><a href='hino/292/292.xml'>Como foi para o céu, Jesus Cristo há de vir</a>: 292</li>
					<li><a href='hino/226/226.xml'>Conta-me a história de Cristo</a>: 226</li>
				</ul>
			</li>
			<li><span id='d'>D</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/371/371.xml'>Da Bíblia a luz celeste</a>: 371</li>
					<li><a href='hino/298/298.xml'>Da Igreja o fundamento</a>: 298</li>
					<li><a href='hino/034/034.xml'>Demos com alegre som</a>: 034 *</li>
					<li><a href='hino/156/156.xml'>Descansa, ó alma, eis o Senhor ao lado</a>: 156</li>
					<li><a href='hino/018/018.xml'>Deus dos antigos, cuja forte mão</a>: 018</li>
					<li><a href='hino/004/004.xml'>Deus está no templo</a>: 004 *</li>
					<li><a href='hino/368/368.xml'>Deus vos guarde pelo seu poder</a>: 368</li>
					<li><a href='hino/340/340.xml'>Disposta a mesa, ó Salvador</a>: 340</li>
					<li><a href='hino/282/282.xml'>Disse Jesus: “Ide por todo o mundo</a>: 282</li>
				</ul>
			</li>
			<li><span id='e'>E</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/317/317.xml'>Eia, crentes destemidos</a>: 317</li>
					<li><a href='hino/240/240.xml'>Eis dos anjos a harmonia</a>: 240</li>
					<li><a href='hino/198/198.xml'>Eis mensagem do Senhor, Aleluia</a>: 198</li>
					<li><a href='hino/274/274.xml'>Eis morto o Salvador</a>: 274</li>
					<li><a href='hino/231/231.xml'>Eis que um anjo proclamou o primeiro Natal</a>: 231</li>
					<li><a href='hino/225/225.xml'>Eis-me, ó Salvador, aqui</a>: 225</li>
					<li><a href='hino/003/003.xml'>Eterno Pai teu povo congregado</a>: 003 *</li>
					<li><a href='hino/068/068.xml'>Eu creio, Senhor, na divina promessa</a>: 068</li>
					<li><a href='hino/229/229.xml'>Eu venho a vós, dos altos céus</a>: 229</li>
				</ul>
			</li>
			<li><span id='f'>F</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/148/148.xml'>Finda-se este dia que meu Pai me deu</a>: 148</li>
					<li><a href='hino/399/399.xml'>Findado agora o culto, ó Deus</a>: 399</li>
					<li><a href='hino/177/177.xml'>Firme nas promessas do meu Salvador</a>: 177</li>
					<li><a href='hino/299/299.xml'>Fortalece a tua Igreja</a>: 299</li>
				</ul>
			</li>
			<li><span id='g'>G</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/005/005.xml'>Glória seja ao Pai</a>: 005</li>
					<li><a href='hino/062/062.xml'>Graças te dou por tudo que me deste</a>: 062</li>
				</ul>
			</li>
			<li><span id='h'>H</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/326/326.xml'>Homens presbiterianos do Brasil</a>: 326</li>
				</ul>
			</li>
			<li><span id='j'>J</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/048/048.xml'>Jesus, quão infinito é teu divino amor</a>: 048</li>
					<li><a href='hino/037/037.xml'>Jesus, teu nome é santo</a>: 037</li>
					<li><a href='hino/001/001.xml'>Justo é o Senhor em seus santos caminhos</a>: 001</li>
				</ul>
			</li>
			<li><span id='l'>L</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/016/016.xml'>Louvai a Deus</a>: 016</li>
					<li><a href='hino/047/047.xml'>Louvamos-te, ó Deus, pelo dom de Jesus</a>: 047</li>
				</ul>
			</li>
			<li><span id='m'>M</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/135/135.xml'>Mais de Cristo eu quero ter</a>: 135</li>
					<li><a href='hino/104/104.xml'>Mais do que milhares é Cristo, meu bom Mestre</a>: 104</li>
					<li><a href='hino/116/116.xml'>Mais perto quero estar, meu Deus, de ti</a>: 116</li>
					<li><a href='hino/254/254.xml'>Mestre, o mar se revolta</a>: 254</li>
					<li><a href='hino/222/222.xml'>Meu Senhor, sou teu, tua voz ouvi</a>: 222</li>
					<li><a href='hino/038/038.xml'>Mil vezes mil louvores rendamos a Jesus</a>: 038</li>
					<li><a href='hino/379/379.xml'>Minha Pátria para Cristo</a>: 379</li>
					<li><a href='hino/395/395.xml'>Mui felizes nos correm os dias</a>: 395</li>
				</ul>
			</li>
			<li><span id='n'>N</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/171/171.xml'>Na forte aflição, perigo e dor</a>: 171</li>
					<li><a href='hino/346/346.xml'>Não nas mãos, mas em minha alma</a>: 346</li>
					<li><a href='hino/320/320.xml'>Não somente ao se fazer trabalho singular</a>: 320</li>
					<li><a href='hino/239/239.xml'>Nasce Jesus! Fonte de luz</a>: 239</li>
					<li><a href='hino/243/243.xml'>Noite de Paz! Noite de Amor</a>: 243</li>
					<li><a href='hino/332/332.xml'>Nossos filhos te pertencem</a>: 332</li>
					<li><a href='hino/064/064.xml'>Nunca meus lábios cessarão, ó Cristo</a>: 064</li>
				</ul>
			</li>
			<li><span id='o'>O</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/030/030.xml'>Ó Deus, ó Providência! Com teu real poder</a>: 030 *</li>
					<li><a href='hino/031/031.xml'>Ó Deus, ó Providência! Sem ti não há viver</a>: 031 *</li>
					<li><a href='hino/002/002.xml'>O Senhor está no seu santo templo</a>: 002</li>
					<li><a href='hino/375/375.xml'>O ano velho já termina</a>: 375</li>
					<li><a href='hino/029/029.xml'>Ó minha alma, a Deus bendize</a>: 029 *</li>
					<li><a href='hino/230/230.xml'>Ó! Vinde fiéis, triunfantes e alegres</a>: 230</li>
					<li><a href='hino/264/264.xml'>Oh! Fronte ensangüentada</a>: 264</li>
					<li><a href='hino/146/146.xml'>Oh! Quão preciosa e rica promessa</a>: 146</li>
				</ul>
			</li>
			<li><span id='p'>P</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/139/139.xml'>Para altos montes olharei</a>: 139</li>
					<li><a href='hino/131/131.xml'>Para seres santo, tempo hás de tomar</a>: 131</li>
					<li><a href='hino/154/154.xml'>Pelo vale escuro seguirei, Jesus</a>: 154</li>
					<li><a href='hino/151/151.xml'>Pelos bosques e campinas</a>: 151</li>
					<li><a href='hino/268/268.xml'>Pendurado no madeiro</a>: 268</li>
					<li><a href='hino/114/114.xml'>Peregrinando por sobre os montes</a>: 114</li>
					<li><a href='hino/128/128.xml'>Preciosas são as horas</a>: 128</li>
				</ul>
			</li>
			<li><span id='q'>Q</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/147/147.xml'>Quando à alma sequiosa</a>: 147</li>
					<li><a href='hino/297/297.xml'>Quando lá dos céus descendo</a>: 297</li>
					<li><a href='hino/144/144.xml'>Que segurança tenho em Jesus</a>: 144</li>
					<li><a href='hino/234/234.xml'>Quem é o pequeno a repousar</a>: 234</li>
				</ul>
			</li>
			<li><span id='r'>R</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/136/136.xml'>Rocha eterna, meu Jesus</a>: 136</li>
					<li><a href='hino/373/373.xml'>Rompe a aurora! Vai-se embora</a>: 373</li>
					<li><a href='hino/266/266.xml'>Rude cruz se erigiu</a>: 266</li>
				</ul>
			</li>
			<li><span id='s'>S</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/084/084.xml'>Santo Espírito de amor</a>: 084</li>
					<li><a href='hino/012/012.xml'>Santo! Santo! Santo</a>: 012</li>
					<li><a href='hino/011/011.xml'>Santo! Santo! Santo! Deus Onipotente</a>: 011</li>
					<li><a href='hino/052/052.xml'>Saudai o nome de Jesus</a>: 052</li>
					<li><a href='hino/190/190.xml'>Se amarga for aqui a vida</a>: 190</li>
					<li><a href='hino/063/063.xml'>Se da vida as vagas procelosas são</a>: 063</li>
					<li><a href='hino/013/013.xml'>Se nos cega o sol ardente</a>: 013</li>
					<li><a href='hino/108/108.xml'>Se paz a mais doce me deres gozar</a>: 108</li>
					<li><a href='hino/145/145.xml'>Seguro estou, não tenho temor do mal</a>: 145</li>
					<li><a href='hino/161/161.xml'>Sei que o melhor Amigo é Cristo</a>: 161</li>
					<li><a href='hino/269/269.xml'>Seja bendito o Cordeiro</a>: 269</li>
					<li><a href='hino/017/017.xml'>Seja louvado o Deus supremo</a>: 017</li>
					<li><a href='hino/049/049.xml'>Sempre vencendo, mui vitorioso</a>: 049</li>
					<li><a href='hino/026/026.xml'>Senhor meu Deus, quando eu maravilhado</a>: 026</li>
					<li><a href='hino/071/071.xml'>Sim, sofrimento te causei, ó Deus</a>: 071</li>
					<li><a href='hino/093/093.xml'>Somente ponho a minha fé</a>: 093</li>
					<li><a href='hino/066/066.xml'>Sonda-me, ó Deus, o coração</a>: 066</li>
					<li><a href='hino/067/067.xml'>Sonda-me, ó Deus, pois vês meu coração</a>: 067</li>
					<li><a href='hino/288/288.xml'>Sou forasteiro aqui, em terra estranha estou</a>: 288</li>
				</ul>
			</li>
			<li><span id='t'>T</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/035/035.xml'>Teu culto agora, aqui, Senhor</a>: 035 *</li>
					<li><a href='hino/032/032.xml'>Tu és fiel, Senhor, ó Pai celeste</a>: 032</li>
					<li><a href='hino/152/152.xml'>Tu me sondaste a mim, ó Deus</a>: 152</li>
					<li><a href='hino/218/218.xml'>Tua vontade faze, ó Senhor</a>: 218</li>
					<li><a href='hino/015/015.xml'>Tua, ó Deus, é toda a grandeza</a>: 015</li>
					<li><a href='hino/028/028.xml'>Tuas obras te coroam</a>: 028</li>
					<li><a href='hino/A/A.xml'>Tudo vem de ti Senhor</a>: A</li>
				</ul>
			</li>
			<li><span id='u'>U</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/247/247.xml'>Uma estrela cintilante</a>: 247</li>
				</ul>
			</li>
			<li><span id='v'>V</span> <a href='#conteudo'>topo</a>
				<ul>
					<li><a href='hino/014/014.xml'>Vamos nós louvar a Deus, Vamos, vamos</a>: 014</li>
					<li><a href='hino/315/315.xml'>Vamos nós trabalhar, somos servos de Deus</a>: 315</li>
					<li><a href='hino/362/362.xml'>Vejo no céu, esplendente</a>: 362</li>
					<li><a href='hino/367/367.xml'>Vinde meninos! Vinde a Jesus</a>: 367</li>
					<li><a href='hino/237/237.xml'>Vinde, cantai! Jesus nasceu</a>: 237</li>
					<li><a href='hino/010/010.xml'>Vós criaturas de Deus Pai</a>: 010 *</li>
					<li><a href='hino/193/193.xml'>Vou à pátria - eu, peregrino -</a>: 193</li>
				</ul>
			</li>
		</ul>
